namespace FriendlyEnum;

public static class GeneratorConstants
{
    public const string FriendlyEnumAttributeName = "FriendlyEnumAttribute";
    public const string FriendlyNameAttributeName = "FriendlyNameAttribute";
    public const string ExtensionClassName = "FriendlyEnumExtensions";

    public const string GeneratorAttributeSourceCode =
        $$"""
          // <auto-generated/>
          [System.AttributeUsage(System.AttributeTargets.Enum, AllowMultiple = false)]
          public class {{FriendlyEnumAttributeName}} : System.Attribute
          {
          }
          """;

    public const string FriendlyNameAttributeSourceCode =
        $$"""
          // <auto-generated/>
          [System.AttributeUsage(System.AttributeTargets.Field, AllowMultiple = false)]
          public class {{FriendlyNameAttributeName}} : System.Attribute
          {
              public string Value { get; set; }
          }
          """;
}